---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 770360740330999808-WibQ7YqH8lhBMloI2fL8hAvVrWEK99V
:access_token_secret: TUMSqdtRYoYqxbBGrtsgHBjH5HJWe6KrWZVMLkRjMXrmw
